name: '이슈 생성'
description: '이슈 생성과 동시에 Jira와 연동됩니다.'
title: '이슈 제목'
body:
  - type: input
    id: epicId	# 상위 epic 키
    attributes:
      label: '💎 에픽 ID'
      description: '에픽 ID를 입력해주세요'
      placeholder: 'KAN-1'
    validations:
      required: true

  - type: input
    id: dueDate
    attributes:
      label: '🗓️ 마감일'
      placeholder: '2025-05-07'
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: '📝 상세 내용'
      description: '이슈에 대해서 설명해주세요'
    validations:
      required: false
